# Setup
title:               Stefan Inzer
tagline:             'stxnre'
description:         'PhD Student in Statistics at the University of Washington'
url:                 http://stxnre.github.io
# baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Stefan Inzer
  linkedin:          https://www.linkedin.com/in/stefan-inzer/
 # url:               https://twitter.com/mdo
  email:             sinzer@uw.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
